export type ChecklistItem = {
  id: string;
  label: string;
};

export type ChecklistCategory = {
  id: string;
  title: string;
  items: ChecklistItem[];
};

export const ZABITA_CHECKLISTS: ChecklistCategory[] = [
  {
    id: "asci_kofteci",
    title: "Aşçı ve Köfteci",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dâhilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Çalışanların temiz iş önlüğü giymiş olması" },
      { id: "12", label: "Şehir şebekesine bağlı soğuk ve sıcak su tertibatının olması" },
      { id: "13", label: "İşyeri içerisi mozaik karo vb. malzemeden olmalı" },
      { id: "14", label: "İşyerinin duvarları fayans vb. tabanı karo mozaik vb. olmalı" },
      { id: "15", label: "İşyeri tezgâhının üstü mermer olmalı" },
      { id: "16", label: "Yeteri kadar lavabosunun olması" },
      { id: "17", label: "Lavaboda sabun bulundurması" },
      { id: "18", label: "İşyeri ocağı üzerinde yeterli davlumbaz bulunmalı" },
      { id: "19", label: "Bulaşık yıkama yerinin olması" },
      { id: "20", label: "İşyerinde yeterli WC. Bulunmalı" },
      { id: "21", label: "Gider suyunun kanala bağlanması" },
      { id: "22", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "23", label: "İşyerinde buzdolabı bulunmalı" },
      { id: "24", label: "Bu gibi İşyerlerinde camekân olmalı" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "bakkal",
    title: "Bakkal",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Belediye vergi levhası" },
      { id: "4", label: "Hafta tatil ruhsatı" },
      { id: "5", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "6", label: "İşyeri dâhilinin genel temizliği" },
      { id: "7", label: "Fiyat bildirir etiketi" },
      { id: "8", label: "Yangın tüpü" },
      { id: "9", label: "Ecza dolabı" },
      { id: "10", label: "Boya-badana durumu" },
      { id: "11", label: "Tütün mamulleri satış izin belgesi" },
      { id: "12", label: "İş önlüğü" },
      { id: "13", label: "Kaldırım işgali" },
      { id: "14", label: "Terazi bulundurulması ve yıllık ayar kontrolü" },
      { id: "15", label: "Sokak Cephesi camekân durumu" },
      { id: "16", label: "Haşaratla mücadele" },
      { id: "17", label: "Açılış kapanış saatlerine riayet" },
      { id: "18", label: "Gıda maddelerinin son kullanma tarihleri" },
      { id: "19", label: "Yeterli havalandırma tertibatının olması" },
      { id: "20", label: "Ağzı kapaklı çöp kovası" },
      { id: "21", label: "Şebekeye bağlı Lavabosunda sıvı sabun ve kâğıt havlu" },
      { id: "22", label: "Kese kâğıdı veya Beyaz Poşet Kullanımı" },
      { id: "23", label: "Duvarda ‘Sigara İçilmez’ Levhasının asılı olması" },
      { id: "24", label: "Gıda maddeleri ile diğer maddelerin ayrı reyonlarda satışı" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "bar",
    title: "Bar",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dâhilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Bu gibi işyerleri daima kâgir binalarda olmalı" },
      { id: "12", label: "İşyeri tabanı mermer, mozaik vb. madde olmalı" },
      { id: "13", label: "Bu yerler kullanım amaçları göre bölümlere ayrılmalı" },
      { id: "14", label: "Antre en az 5 metrekare olmalı" },
      { id: "15", label: "Bay ve bayanlar için ayrı WC.' lerin olması" },
      { id: "16", label: "WC. ve Lavabolarda yeteri kadar sıvı sabun olmalı" },
      { id: "17", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "18", label: "Kapasiteye uygun vestiyer olmalı" },
      { id: "19", label: "Haşaratla mücadele edilmeli" },
      { id: "20", label: "Personel, konsomatris ve artistlerin soyunma odası olmalı" },
      { id: "21", label: "Bu gibi işyerlerinin duvarları fayans vb. malzeme olmalı" },
      { id: "22", label: "Sıcak ve soğuk su tertibatı olmalı" },
      { id: "23", label: "Gider suyunun kanala bağlı olması" },
      { id: "24", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "cay_ocagi",
    title: "Çay Ocağı",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Belediye vergi levhası" },
      { id: "4", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "5", label: "İşyeri dâhilinin genel temizliği" },
      { id: "6", label: "Fiyat tarifesi" },
      { id: "7", label: "Yangın tüpü" },
      { id: "8", label: "Ecza dolabı" },
      { id: "9", label: "Duvarların kolay temizlenir madde ile kaplı olması" },
      { id: "10", label: "Zeminin fayans, mozaik vb. sert malzeme olması" },
      { id: "11", label: "Masraf suyunun menfeze tahliyesi için ızgaralı sifon olması" },
      { id: "12", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "13", label: "Şehir içme su tesisatının olması" },
      { id: "14", label: "Ocağın cam ile tabure ve sehpa konulan alandan ayrı olması" },
      { id: "15", label: "Ocak tezgâhının mermer veya fayans olması" },
      { id: "16", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "17", label: "Çatlak, kırık fincan, bardak vb. ile paslı ve kırık kaşık olmaması" },
      { id: "18", label: "Çalışanların temiz iş önlüğü giymiş olması" },
      { id: "19", label: "Isıtma, soğutma ve havalandırma için yeterli tertibatın olması" },
      { id: "20", label: "En az bir adet havalandırmalı WC olması" },
      { id: "21", label: "Lavaboda sıvı sabunluk, kâğıt havlu ve ayna olması" },
      { id: "22", label: "İşyerinde gizli bölme, başka geçiş vb. olmaması" },
      { id: "23", label: "Duvarda “sigara içilmez” levhasının asılı olması" },
      { id: "24", label: "Dışarıya açılan pencere ve kapılarda sineklik teli olması" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "ekmek_satis",
    title: "Ekmek Satış Yeri",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Belediye vergi levhası" },
      { id: "4", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "5", label: "İşyeri dâhilinin genel temizliği" },
      { id: "6", label: "Fiyat bildirir tarife" },
      { id: "7", label: "Yangın tüpü" },
      { id: "8", label: "Ecza dolabı" },
      { id: "9", label: "Boya-badana durumu" },
      { id: "10", label: "İş önlüğü" },
      { id: "11", label: "Ağzı kapaklı çöp kovası" },
      { id: "12", label: "Bone, eldiven, galoş durumu" },
      { id: "13", label: "Haşaratla mücadele edilmeli" },
      { id: "14", label: "Ambalaj kağıdı" },
      { id: "15", label: "Duvarda’ Sigara İçilmez Levhası’ olması" },
      { id: "16", label: "Satılan ekmekler masaların üstünde satılmalı" },
      { id: "17", label: "Terazi bulundurulup yıllık muayenesinin yapılması" },
      { id: "18", label: "Taze ve bayat Francalalar farklı yerlere konulmalı" },
      { id: "19", label: "Mevzuatın öngördüğü diğer hükümler vb" },
    ],
  },
  {
    id: "fast_food",
    title: "Fast Food, Kafeterya ve Pizza Satış Yeri",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dahilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Çalışanların temiz iş önlüğü giymiş olması" },
      { id: "12", label: "Şehir şebekesine bağlı soğuk ve sıcak su tertibatının olması" },
      { id: "13", label: "İşyeri tabanı mozaik karo vb. malzemeden olmalı" },
      { id: "14", label: "İşyerinin duvarları kolay temizlenir madde ile kaplı olmalı" },
      { id: "15", label: "İşyeri tezgahının üstü mermer ve davlumbazlı olmalı" },
      { id: "16", label: "Yeteri kadar lavabosunun olması" },
      { id: "17", label: "Lavaboda sabun bulundurması" },
      { id: "18", label: "İşyeri ocağı üzerinde yeterli davlumbaz bulunmalı" },
      { id: "19", label: "Bulaşık yıkama yerinin olması" },
      { id: "20", label: "İşyerinde yeterli WC. Bulunmalı" },
      { id: "21", label: "Bu işyerlerinde çalışanlara yetecek kadar giyinme odası olmalı" },
      { id: "22", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "23", label: "İşyerinde buzdolabı bulunmalı" },
      { id: "24", label: "Bu gibi İşyerlerinde camekân olmalı" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb" },
    ],
  },
  {
    id: "erkek_berberi",
    title: "Erkek Berberi",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dâhilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Bu gibi yerlerin tabanı mermer mozaik vb. olmalı" },
      { id: "12", label: "Bu gibi yerlerin duvarları fayans mermer vb. olmalı" },
      { id: "13", label: "Bu gibi işyerlerinin önü camekânlı olmalı" },
      { id: "14", label: "Bu gibi işyerlerinde havlular beyaz renkli olmalı" },
      { id: "15", label: "Pamuk ve pudra bir defa kullanılıp atılmalı" },
      { id: "16", label: "Kullanılan aletler dezenfekte edilmeli" },
      { id: "17", label: "Çalışanlar iş önlüğü giymeli" },
      { id: "18", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "19", label: "Lavaboda yeterli sıcak ve soğuk su tertibatının olması" },
      { id: "20", label: "Hafta tatil ruhsatı" },
      { id: "21", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "kadin_berberi",
    title: "Kadın Berberi ve Güzellik Merkezi",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dâhilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Bu gibi yerlerin tabanı mermer mozaik vb. olmalı" },
      { id: "12", label: "Bu gibi yerlerin duvarları fayans mermer vb. olmalı" },
      { id: "13", label: "Bu gibi işyerlerinin önü camekânlı olup tül perdeli olmalı" },
      { id: "14", label: "Bu gibi işyerlerinde havlular beyaz renkli" },
      { id: "15", label: "Saç kesim ve düzeltme yerlerinin minimum 12 metre olması" },
      { id: "16", label: "Kullanılan aletler dezenfekte edilmeli" },
      { id: "17", label: "Çalışanlar iş önlüğü giymeli" },
      { id: "18", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "19", label: "Lavaboda yeterli sıcak ve soğuk su tertibatının olması" },
      { id: "20", label: "Boya vs hazırlanmasına mahsus sabit tezgahlı yer olmalı" },
      { id: "21", label: "WC Lavabolarda yeteri kadar sıvı sabun olmalı" },
      { id: "22", label: "Hafta tatil ruhsatı" },
      { id: "23", label: "Bu işyerlerinde Erkek Berberleri hükümleri aynen uygulanır" },
      { id: "24", label: "Gider suyunun kanala bağlı olması" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "hamam_sauna",
    title: "Hamam, Duşlu Banyo ve Sauna",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dâhilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Bu gibi yerlerin tabanı mermer mozaik vb. olmalı" },
      { id: "12", label: "Bu gibi yerlerin duvarları fayans mermer vb. olmalı" },
      { id: "13", label: "Soyunma kabinleri merkezi sistemle ısıtılmalı" },
      { id: "14", label: "Bu işyerleri daima badana ve boyalı olmalı" },
      { id: "15", label: "Kullanılan havlu takımları her defasında yenilenmeli" },
      { id: "16", label: "Gider suyunun kanala bağlı olması" },
      { id: "17", label: "Hamamlarda çiğ köfte yapılıp yenilmemeli" },
      { id: "18", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "19", label: "Lavaboda yeterli sıcak ve soğuk su tertibatının olması" },
      { id: "20", label: "Haşaratla mücadele edilmeli" },
      { id: "21", label: "Bu gibi işyerlerinde yeterli WC olmalı" },
      { id: "22", label: "WC. Lavabolarda yeteri kadar sıvı sabun olmalı" },
      { id: "23", label: "Bu işyerlerinde kirli ve temiz takımlar ayrı muhafaza edilmeli" },
      { id: "24", label: "Duş tertibatı olan en az iki oda bulundurulmalı" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "kasap",
    title: "Kasap",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dahilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Çalışanların temiz iş önlüğü giymiş olması" },
      { id: "12", label: "Etlerin damgalı olup olmadığı" },
      { id: "13", label: "Koyun ve kuzu etlerinin mor renk damgalı olması" },
      { id: "14", label: "Keçi ve oğlak etlerinin kırmızı renk damgalı olması" },
      { id: "15", label: "Kasapların ön kısmının camekân olması" },
      { id: "16", label: "Lavaboda sabun bulundurması" },
      { id: "17", label: "Hazır kıyma bulundurmaması" },
      { id: "18", label: "Etlerin türleri belirtilerek dolapta muhafaza edilmesi" },
      { id: "19", label: "Duvarda “Sigara içilmez” levhasının asılı olması" },
      { id: "20", label: "Etlerin ambalaj kağıdına sarılması" },
      { id: "21", label: "Kıyma makinesinin olması" },
      { id: "22", label: "Tezgah ve kütüklerin temiz olması" },
      { id: "23", label: "Kaçak kesim yapılmaması" },
      { id: "24", label: "Hazırda parça et bulundurulmaması" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "lokanta",
    title: "Lokanta",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "4", label: "İşyeri dahilinin genel temizliği" },
      { id: "5", label: "Fiyat tarifesi" },
      { id: "6", label: "Yangın tüpü" },
      { id: "7", label: "Ecza dolabı" },
      { id: "8", label: "İçine çöp poşeti geçirilmiş ağzı kapaklı çöp kovasının olması" },
      { id: "9", label: "Kullanılan alet ve edevatın temiz olması" },
      { id: "10", label: "Isıtma, soğutma ve havalandırma için yeterli tesisatın olması" },
      { id: "11", label: "Çalışanların temiz iş önlüğü giymiş olması" },
      { id: "12", label: "Gider suyunun kanala bağlı olması" },
      { id: "13", label: "Ocağın üzerinde davlumbaz olması" },
      { id: "14", label: "Yeteri kadar lavabo olması" },
      { id: "15", label: "Lavaboda sıvı sabunluk, kağıt havlu ve ayna olması" },
      { id: "16", label: "Tezgah üstlerinin mermer olması" },
      { id: "17", label: "Bulaşık yıkama yerlerinin ayrı olması" },
      { id: "18", label: "Lokantaların sokağa bakan kısmının camekânlı olması" },
      { id: "19", label: "Erkek ve bayan WC’lerinin ayrı olması" },
      { id: "20", label: "Duvarda “Sigara içilmez” levhasının olması" },
      { id: "21", label: "Hazırlama ve pişirme bölümlerinin olması" },
      { id: "22", label: "En az bir kişinin aşçı Ustalık belgesi olması" },
      { id: "23", label: "Masaların üzerinde örtü peçete olması" },
      { id: "24", label: "Çatal, kaşık ve bıçakların paslanmaz çelikten olması" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "manav",
    title: "Manav",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Belediye vergi levhası" },
      { id: "4", label: "Hafta tatil ruhsatı" },
      { id: "5", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "6", label: "İşyeri dâhilinin genel temizliği" },
      { id: "7", label: "Fiyat bildirir etiket" },
      { id: "8", label: "Yangın tüpü" },
      { id: "9", label: "Ecza dolabı" },
      { id: "10", label: "Boya-badana durumu" },
      { id: "11", label: "Rafların durumu yerden en az 30 Cm yüksek olmalı" },
      { id: "12", label: "İş önlüğü" },
      { id: "13", label: "Kaldırım işgali" },
      { id: "14", label: "Terazi bulundurulması ve yıllık ayar kontrolü" },
      { id: "15", label: "Gider suyu kanalizasyon bağlantısı" },
      { id: "16", label: "Haşere ile mücadele" },
      { id: "17", label: "İşyeri tabanı kolay temizlenebilir materyal" },
      { id: "18", label: "Yaş meyve ve sebze harici satış" },
      { id: "19", label: "Şehir şebekesine bağlı su sistemi ve lavabo" },
      { id: "20", label: "Ağzı kapaklı çöp kovası" },
      { id: "21", label: "Lavaboda sıvı sabun ve kağıt havlu" },
      { id: "22", label: "Yıkanmadan pişirilmeden yenen ürün kapalı kapta bulunması" },
      { id: "23", label: "Kese Kağıdı ve Beyaz Poşet Kullanımı" },
      { id: "24", label: "Duvarda “Sigara içilmez” levhası" },
      { id: "25", label: "Mevzuat hükümlerinin öngördüğü maddeler vb." },
    ],
  },
  {
    id: "market",
    title: "Market, Süper Market",
    items: [
      { id: "1", label: "İşyeri açma ve çalıştırma ruhsatı" },
      { id: "2", label: "Esnaf kontrol defteri" },
      { id: "3", label: "Belediye vergi levhası" },
      { id: "4", label: "Hafta tatil ruhsatı" },
      { id: "5", label: "Çalışanların esnaf sağlık karneleri" },
      { id: "6", label: "İşyeri dâhilinin genel temizliği" },
      { id: "7", label: "Fiyat bildirir etiket" },
      { id: "8", label: "Yangın tüpü" },
      { id: "9", label: "Ecza dolabı" },
      { id: "10", label: "Boya-badana durumu" },
      { id: "11", label: "İş önlüğü, bone, eldiven, galoş" },
      { id: "12", label: "Kaldırım işgali" },
      { id: "13", label: "Terazi bulundurulması ve yıllık ayar kontrolü" },
      { id: "14", label: "Havalandırma tertibatı aspiratör sistemi" },
      { id: "15", label: "Haşaratla mücadele" },
      { id: "16", label: "Gıda maddelerinin son kullanma tarihleri" },
      { id: "17", label: "Şehir şebekesine bağlı su sistemi ve sıcak su tertibatı" },
      { id: "18", label: "Ağzı kapaklı çöp kovası" },
      { id: "19", label: "Lavaboda sıvı sabun ve kağıt havlu" },
      { id: "20", label: "Et reyonlarında veteriner ve veteriner kontrol defteri" },
      { id: "21", label: "Malların stok deposu, soğutma odası, personel servisi" },
      { id: "22", label: "Pişmemiş deniz ürünleri için ayrı vitrinli buzdolabı" },
      { id: "23", label: "İşyeri içindeki imalatla ilgili ruhsat durumu" },
      { id: "24", label: "Duvarda “Sigara içilmez” levhası" },
      { id: "25", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
  {
    id: "pazar",
    title: "Pazar Denetimi",
    items: [
      { id: "1", label: "Pazar esnafının Pazar vesikası var mı?" },
      { id: "2", label: "Pazar esnafı pazar yeri sınırından dışarıya taşımıyor mu?" },
      { id: "3", label: "Kavun, karpuz biber sergisi için belediyeden izin alınmış mı?" },
      { id: "4", label: "Pazarcılar çöp kabı bulundurup çöpü düzenli atıyor mu?" },
      { id: "5", label: "Pazarcılar çevreyi temiz tutuyor mu?" },
      { id: "6", label: "Pazarcı esnafının sağlık karnesi var mı?" },
      { id: "7", label: "Kontrol edilmiş ölçü aleti bulunduruyor mu?" },
      { id: "8", label: "Pazarcı gürültüyle çevreyi rahatsız etmiyor mu?" },
      { id: "9", label: "Pazarcılar bölgedeki sabit esnaf önlerini işgal etmiyor mu?" },
      { id: "10", label: "Pazar yerinde duvarlara çivi çakıp çevreye zarar vermiyor mu?" },
      { id: "11", label: "Pazar esnafı pazar yerlerinde yıkım, tadilat vb. yapmıyor mu?" },
      { id: "12", label: "Pazar yerlerinde geçiş trafiğini engellemiyor mu?" },
      { id: "13", label: "Esnaf Pazarda sabah 07.00 itibarıyla faaliyete geçiyor mu?" },
      { id: "14", label: "Esnaf Pazar yerlerini akşam hava kararınca kaldırıyor mu?" },
      { id: "15", label: "Yıkanmadan, soyulmadan yenen besin maddeleri açıkta satılmıyor mu?" },
      { id: "16", label: "Sattığı ürüne fiyat etiketi koyuyor mu?" },
      { id: "17", label: "Pazar esnafı önlük bone takıyor mu?" },
      { id: "18", label: "Pazar kurarken yerini komşusunu rahatsız etmeden kuruyor mu?" },
      { id: "19", label: "Pazarcı esnafı belediye ile yıllık sözleşmesini yapıyor mu?" },
      { id: "20", label: "Pazar yeri devir tahsis işlemleri kurallara uygun yapılıyor mu?" },
      { id: "21", label: "Pazarcı esnafı kendisine tahsis edilen alanın dışına taşımıyor mu?" },
      { id: "22", label: "Esnaf pazar dağılırken kendi etrafını düzenliyor mu?" },
      { id: "23", label: "Ürünleri tartarken gramlar görülecek yerde ve düzgün tartıyor mu?" },
      { id: "24", label: "Mevzuatın öngördüğü diğer hükümler vb." },
    ],
  },
];

/**
 * Calculates penalty points and recommended administrative action based on unchecked (failed) items
 */
export function calculatePenalty(inspectionTypeId: string, checklistData: Record<string, boolean>) {
  const category = ZABITA_CHECKLISTS.find((c) => c.id === inspectionTypeId);
  if (!category) return { penaltyPoints: 0, recommendedAction: "Uygun", missingItemsCount: 0 };

  let penaltyPoints = 0;
  let missingItemsCount = 0;

  category.items.forEach((item) => {
    // If item is unchecked (false or undefined), it is missing/failed
    if (checklistData[item.id] !== true) {
      missingItemsCount++;
      const lower = item.label.toLowerCase();
      
      // Assign weight based on item severity
      if (lower.includes("ruhsat") || lower.includes("tütün") || lower.includes("tarih")) {
        penaltyPoints += 30; // Critical legal compliance
      } else if (lower.includes("yangın") || lower.includes("sağlık") || lower.includes("hijyen") || lower.includes("bone")) {
        penaltyPoints += 20; // Health & safety
      } else if (lower.includes("temizlik") || lower.includes("fiyat") || lower.includes("etiket") || lower.includes("önlük")) {
        penaltyPoints += 15; // General rules
      } else {
        penaltyPoints += 10; // Standard items
      }
    }
  });

  let recommendedAction = "Uygun";
  if (penaltyPoints > 0 && penaltyPoints <= 25) {
    recommendedAction = "Sözlü / Yazılı Uyarı";
  } else if (penaltyPoints > 25 && penaltyPoints <= 50) {
    recommendedAction = "1. İhtar (7 Gün Süre)";
  } else if (penaltyPoints > 50 && penaltyPoints <= 85) {
    recommendedAction = "İdari Para Cezası";
  } else if (penaltyPoints > 85) {
    recommendedAction = "Geçici Faaliyetten Men (Mühürleme)";
  }

  return { penaltyPoints, recommendedAction, missingItemsCount };
}
